### ISSUE TITLE
Support in-function statics with identical names in the same file

### ISSUE THREAD

**Issue by hensldm** [simonlindholm/asm-processor#23]
From discord:
"It is asm_processor's deduplication logic which uses the original symbols name that causes the issue. Note this a problem in general even without emitting global with filename."
"This is to support statics being referred to from within GLOBAL_ASM btw. We could decide to give up on that, or preferably, figure out how to determine from mdebug whether a static is in global scope"

**Comment by simonlindholm** [comment]
I found a way to distinguish in-function statics from ones in global scope, and made it so that the former ones get :1, :2, ... added to their names.
