### ISSUE TITLE
`Error: symbol ".text" defined twice` on DKR when using `mips-elf-as`

### ISSUE THREAD

**Issue by DavidSM64** [simonlindholm/asm-processor#25]
The error `Error: symbol ".text" defined twice` appears for two files when trying to build the DKR decomp on my raspberry pi. Works perfectly fine under ubuntu in WSL.

Ryan Dwyer also has this issue when running on Arch Linux using `mips-elf-as`, but is fine if he used `mips-linux-gnu-as` instead for his assembler. I am also using `mips-elf-as` on my PI.

This issue can be worked around by ignoring `.text` when checking for duplicate symbols in asm_processor.py.

Changing:
```python
                elif s.st_shndx != SHN_UNDEF:
                    raise Failure("symbol \"" + s.name + "\" defined twice")
```
To this:
```python
                elif s.name != ".text" and s.st_shndx != SHN_UNDEF:
                    raise Failure("symbol \"" + s.name + "\" defined twice")
```

The Starfox64 decomp people just remove the error altogether to make it work for Mac systems:

![](https://cdn.discordapp.com/attachments/683041013563916402/1211704547722928178/image.png?ex=65ef2acc&is=65dcb5cc&hm=9e4b61ff3ca8d7a51c7ac0fd20a4b921c90f92b15c30a69ede194c88d5857189&)

----

From what I can tell, `asm_objfile.symtab.symbol_entries` always has these symbols even if they are not used:
```
   .text
   .data
   .bss
   .rodata
   .reginfo
   .MIPS.abiflags
   .pdr
   .gnu.attributes
```
These don't appear with `mips-linux-gnu-as` on my ubuntu distro.

And somehow, the `.text` symbol gets relocated in certain files. This makes it get added to the `new_syms` list, despite `.text` already being defined from `objfile.symtab.symbol_entries`.

The two problematic asm files in DKR are: [func_80031600 from collision.c](https://github.com/DavidSM64/Diddy-Kong-Racing/blob/master/asm/collision/func_80031600.s) and [atan2s from math_utils.c](https://github.com/DavidSM64/Diddy-Kong-Racing/blob/master/asm/math_util/atan2s.s)

I printed out some of the values when it is compiling: https://gist.githubusercontent.com/DavidSM64/b7c0330b169f91c8e63aafffd329c871/raw/e71b0f75d2db85735479d1768c2b2ff6d32b97f1/gistfile1.txt

I hope this all gives you some idea on what the issue could be.

**Comment by DavidSM64** [comment]
Just wanted to let you know that your latest commit did work. 👍

**Comment by simonlindholm** [comment]
> Just wanted to let you know that your latest commit did work. 👍

Excellent! Would have commented here but was at a computer that only had ssh access to GitHub, not browser. Your suggested fix looks good too btw, the committed one just takes it a bit further and allows e.g. local symbols for other sections as well. Thanks for the good bug report!
